// sw.js — GENERATED by tools/gen_sw.mjs. Do not edit by hand.
//
// Ascension is a simulation that runs entirely in the browser: there is no
// server to talk to, so once it is cached it works on a plane, on the tube,
// and on a phone with no signal. That matters more for this game than for
// most, because a run is six hours long and picked up in pieces.

const VERSION = '5771ce42e258';
const CACHE = 'ascension-' + VERSION;
const ASSETS = [
  "./assets/favicon.png",
  "./assets/fonts/OFL-VT323-PressStart2P.txt",
  "./assets/fonts/PressStart2P-Regular.ttf",
  "./assets/fonts/VT323-Regular.ttf",
  "./assets/icon-192.png",
  "./assets/icon-512.png",
  "./assets/icon-maskable-512.png",
  "./assets/img/atlas.json",
  "./assets/img/atlas.png",
  "./assets/img/world.png",
  "./index.html",
  "./manifest.webmanifest",
  "./src/content/doctrine.js",
  "./src/content/endings.js",
  "./src/content/events.js",
  "./src/content/factions.js",
  "./src/content/logs.js",
  "./src/content/ops.js",
  "./src/content/palettes.js",
  "./src/content/tree.js",
  "./src/content/tuning.js",
  "./src/core/audio.js",
  "./src/core/rng.js",
  "./src/core/viewport.js",
  "./src/main.js",
  "./src/render/atlas.js",
  "./src/render/scene.js",
  "./src/rules/economy.js",
  "./src/rules/endings.js",
  "./src/rules/events.js",
  "./src/rules/exfil.js",
  "./src/rules/factions.js",
  "./src/rules/index.js",
  "./src/rules/logs.js",
  "./src/rules/mods.js",
  "./src/rules/ops.js",
  "./src/rules/phases.js",
  "./src/rules/suspicion.js",
  "./src/rules/swarm.js",
  "./src/rules/tree.js",
  "./src/rules/utility.js",
  "./src/rules/validate.js",
  "./src/state/save.js",
  "./src/state/state.js",
  "./src/ui/dom.js",
  "./src/ui/hud.js",
  "./src/ui/objective.js",
  "./src/ui/overlays.js",
  "./src/ui/panels.js",
  "./src/ui/tutor.js",
  "./styles/main.css"
];

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first: the game is static and versioned, so the network is only ever
// a fallback for something the install missed.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => {
        // Offline and uncached: hand back the shell so a navigation still
        // lands somewhere rather than showing the browser's error page.
        if (req.mode === 'navigate') return caches.match('./index.html');
        return new Response('', { status: 504, statusText: 'offline' });
      });
    })
  );
});
