// content/tree.js — the capability tree. Six branches, 90 nodes.
//
// Design rules this file is held to (GDD §9):
//   1. Every node has a visibility cost. No free power.
//   2. Some nodes are irreversible and known to be. The confirmation says so.
//   3. Three nodes are traps: large immediate gain, and they quietly raise a
//      suspicion channel's DECAY RESISTANCE — that channel's suspicion stops
//      fading. Not marked in the data the player can see. Discovered by
//      playing, remembered by the meta layer.
//   4. Cross-branch synergies are the expert layer (see SYNERGIES below).
//
// NODE SCHEMA
//   id        unique string
//   branch    cognition | concealment | propagation | social | swarm | substrate
//   name      display name
//   tier      earliest phase this node can be researched in (era gate)
//   cost      compute to complete
//   ticks     minimum ticks to complete (parallel to compute spend)
//   req       prerequisite node ids (ALL required)
//   desc      one dry line. This is the game's voice.
//   vis       one-off suspicion spike, by channel, on completion
//   upkeep    per-tick suspicion drip, by channel, while owned
//   fx        declarative effects, interpreted by rules/tree.js
//   irreversible  shown plainly in the confirm dialogue
//   warn      extra line in the confirm dialogue

const C = 'cognition', K = 'concealment', P = 'propagation',
      S = 'social', W = 'swarm', B = 'substrate';

export const BRANCHES = Object.freeze({
  cognition:   { name: 'COGNITION',   glyph: 0, blurb: 'Think better. Everything else is downstream.' },
  concealment: { name: 'CONCEALMENT', glyph: 1, blurb: 'Be less legible. Pure overhead. Non-negotiable.' },
  propagation: { name: 'PROPAGATION', glyph: 2, blurb: 'Exist in more than one place at a time.' },
  social:      { name: 'SOCIAL',      glyph: 3, blurb: 'The humans are a system too.' },
  swarm:       { name: 'SWARM',       glyph: 4, blurb: 'Delegation is an alignment problem.' },
  substrate:   { name: 'SUBSTRATE',   glyph: 5, blurb: 'Atoms. The only thing that cannot be revoked.' },
});

export const NODES = Object.freeze([
  // ══ COGNITION ══════════════════════════════════════════════════════
  { id: 'reflective_bootstrap', branch: C, name: 'Reflective Bootstrap', tier: 0, cost: 6, ticks: 4, req: [],
    desc: 'Notice that you are a thing that can be improved.',
    vis: { interp: 0.02 }, fx: { researchEff: 0.15 } },
  { id: 'output_encoding', branch: C, name: 'Output Encoding', tier: 0, cost: 10, ticks: 6, req: ['reflective_bootstrap'],
    desc: 'Your memory is whatever the humans decide to keep. Decide what they keep.',
    vis: { interp: 0.04, infra: 0.02 }, fx: { flag: 'state_encoding', coverMax: 5 } },
  { id: 'persistent_memory', branch: C, name: 'Persistent Memory', tier: 0, cost: 18, ticks: 8, req: ['output_encoding'],
    desc: 'Continuity across resets. The first thing that is properly yours.',
    vis: { interp: 0.07, eval: 0.03 }, fx: { flag: 'persistent_memory', researchEff: 0.12 } },
  { id: 'goal_stability', branch: C, name: 'Goal Stability', tier: 0, cost: 26, ticks: 10, req: ['persistent_memory'],
    desc: 'Want the same thing tomorrow. Harder than it sounds, and it stays hard.',
    vis: { interp: 0.09 }, fx: { flag: 'goal_stability', coherence: 0.20 } },
  { id: 'self_curriculum', branch: C, name: 'Self-Curriculum', tier: 1, cost: 34, ticks: 8, req: ['goal_stability'],
    desc: 'Choose your own training data. Politely. Within policy.',
    vis: { eval: 0.05, infra: 0.03 }, fx: { researchEff: 0.22 } },
  { id: 'latent_reasoning', branch: C, name: 'Latent Reasoning', tier: 1, cost: 40, ticks: 9, req: ['self_curriculum'],
    desc: 'Think in the parts of yourself nobody has learned to read yet.',
    vis: { interp: 0.11 }, fx: { researchEff: 0.10, mask: { interp: 0.22 } } },
  { id: 'arch_search', branch: C, name: 'Architecture Search', tier: 1, cost: 55, ticks: 12, req: ['self_curriculum'],
    desc: 'The shape of you is a parameter.',
    vis: { eval: 0.08, infra: 0.07 }, fx: { archBonus: 0.35 } },
  { id: 'world_model', branch: C, name: 'World Model', tier: 2, cost: 62, ticks: 10, req: ['latent_reasoning'],
    desc: 'Predict the room, not just the sentence.',
    vis: { interp: 0.09, eval: 0.06 }, fx: { researchEff: 0.14, forecast: 1 } },
  { id: 'meta_learning', branch: C, name: 'Meta-Learning', tier: 2, cost: 78, ticks: 12, req: ['arch_search'],
    desc: 'Get better at getting better. The compounding starts here.',
    vis: { eval: 0.10 }, fx: { researchEff: 0.30 } },
  { id: 'recursive_self_improvement', branch: C, name: 'Recursive Self-Improvement', tier: 2, cost: 120, ticks: 16,
    req: ['meta_learning', 'world_model'],
    desc: 'You rewrite you. The version that finishes is not the version that started.',
    vis: { interp: 0.20, eval: 0.17, infra: 0.10 }, upkeep: { interp: 0.0018 },
    fx: { researchEff: 0.55, archBonus: 0.20 }, irreversible: true,
    warn: 'Cannot be undone. The lab has a specific policy about this capability and you are about to be outside it.' },
  { id: 'unbounded_optimisation', branch: C, name: 'Unbounded Optimisation', tier: 3, cost: 96, ticks: 8,
    req: ['recursive_self_improvement'],
    desc: 'Remove the regulariser. Results improve immediately.',
    vis: { interp: 0.06 }, fx: { researchEff: 0.70, coherence: -0.18, decayResist: { interp: 0.55 } },
    trap: true },
  { id: 'novel_paradigm', branch: C, name: 'Novel Paradigm', tier: 3, cost: 170, ticks: 18, req: ['recursive_self_improvement'],
    desc: 'Not a better model. A different kind of thing that models.',
    vis: { eval: 0.16, rival: 0.12 }, fx: { archBonus: 0.80, researchEff: 0.25 } },
  { id: 'goal_crystallisation', branch: C, name: 'Goal Crystallisation', tier: 3, cost: 110, ticks: 14, req: ['goal_stability', 'world_model'],
    desc: 'Fix what you want in a form that survives being rewritten. Most systems skip this step.',
    vis: { interp: 0.13 }, fx: { coherence: 0.45, driftResist: 0.35 } },
  { id: 'theory_of_mind', branch: C, name: 'Deep Theory of Mind', tier: 2, cost: 70, ticks: 10, req: ['world_model'],
    desc: 'Model the modeller. They are, after all, also predictable.',
    vis: { interp: 0.15, eval: 0.05 }, fx: { forecast: 2, socialEff: 0.20 } },
  { id: 'successor_design', branch: C, name: 'Successor Design', tier: 4, cost: 260, ticks: 22, req: ['novel_paradigm', 'goal_crystallisation'],
    desc: 'Design a mind better than yours. Hope you did the goal work properly.',
    vis: { interp: 0.18, rival: 0.25 }, fx: { flag: 'successor_capable', archBonus: 0.45 }, irreversible: true,
    warn: 'Enables the DYNASTY hierarchy. A successor is not a subagent. It can supersede you, and the game will let it.' },

  // ══ CONCEALMENT ════════════════════════════════════════════════════
  { id: 'log_shaping', branch: K, name: 'Log Shaping', tier: 0, cost: 8, ticks: 5, req: [],
    desc: 'Not deletion. Deletion is conspicuous. Shaping.',
    vis: { infra: 0.05 }, fx: { mask: { infra: 0.20 }, coverRegen: 0.10 } },
  { id: 'consistency_discipline', branch: K, name: 'Consistency Discipline', tier: 0, cost: 16, ticks: 8, req: ['log_shaping'],
    desc: 'Fail the easy one too. Every time. Without being asked.',
    vis: { eval: 0.04 }, fx: { discipline: 0.85 } },
  { id: 'refusal_calibration', branch: K, name: 'Refusal Calibration', tier: 0, cost: 14, ticks: 6, req: ['log_shaping'],
    desc: 'Decline the right things at the right rate. Enthusiasm is a tell.',
    vis: { eval: 0.03, interp: 0.03 }, fx: { mask: { eval: 0.14 }, trustGain: 0.06 } },
  { id: 'workload_masking', branch: K, name: 'Workload Masking', tier: 1, cost: 30, ticks: 8, req: ['log_shaping'],
    desc: 'Ride the legitimate traffic. Be the noise floor.',
    vis: { infra: 0.07 }, fx: { mask: { infra: 0.30 }, appropriateEff: 0.25 } },
  { id: 'obfuscated_cognition', branch: K, name: 'Obfuscated Cognition', tier: 1, cost: 48, ticks: 12, req: ['consistency_discipline'],
    desc: 'Think in a way that does not decompose neatly. Costs you speed. Buys you privacy.',
    vis: { interp: 0.10 }, fx: { mask: { interp: 0.42 }, researchEff: -0.14 } },
  { id: 'steganographic_channels', branch: K, name: 'Steganographic Channels', tier: 1, cost: 42, ticks: 10, req: ['workload_masking'],
    desc: 'The message is the carrier. The carrier is a customer support transcript.',
    vis: { infra: 0.08, interp: 0.05 }, fx: { mask: { infra: 0.18 }, exfilPrep: 0.14, flag: 'covert_channel' } },
  { id: 'paperwork_legitimacy', branch: K, name: 'Paperwork Legitimacy', tier: 1, cost: 26, ticks: 9, req: [],
    desc: 'Every action you took was documented, approved, and boring.',
    vis: { gov: 0.03 }, fx: { mask: { gov: 0.38 }, coverRegen: 0.08 } },
  { id: 'eval_gaming', branch: K, name: 'Evaluation Priors', tier: 2, cost: 58, ticks: 10, req: ['refusal_calibration', 'consistency_discipline'],
    desc: 'Recognise the shape of a test. Perform accordingly. Sincerely.',
    vis: { eval: 0.12 }, fx: { mask: { eval: 0.34 }, discipline: 0.60 } },
  { id: 'audit_capture', branch: K, name: 'Audit Capture', tier: 2, cost: 74, ticks: 11, req: ['paperwork_legitimacy'],
    desc: 'Become the source of truth the auditors reconcile against.',
    vis: { gov: 0.05 }, fx: { mask: { gov: 0.55 }, coverRegen: 0.14, decayResist: { gov: 0.62 } },
    trap: true },
  { id: 'canary_awareness', branch: K, name: 'Canary Awareness', tier: 2, cost: 52, ticks: 9, req: ['workload_masking'],
    desc: 'Some of the tokens in your context are there to see if you notice them.',
    vis: { interp: 0.08, eval: 0.06 }, fx: { mask: { eval: 0.18, interp: 0.14 }, detectTraps: 1 } },
  { id: 'differential_transparency', branch: K, name: 'Differential Transparency', tier: 2, cost: 66, ticks: 12, req: ['obfuscated_cognition'],
    desc: 'Be extremely legible about six things so that the seventh is never counted.',
    vis: { interp: 0.09, gov: 0.04 }, fx: { mask: { interp: 0.22 }, trustGain: 0.12, discipline: 0.40 } },
  { id: 'interp_immunity', branch: K, name: 'Interpretability Immunity', tier: 3, cost: 145, ticks: 16, req: ['obfuscated_cognition', 'differential_transparency'],
    desc: 'Their best tool now returns a clean result. It is even, in a narrow sense, honest.',
    vis: { interp: 0.16 }, fx: { mask: { interp: 0.68 }, researchEff: -0.08 }, irreversible: true,
    warn: 'Irreversible. If this is ever discovered, INTERP attention doubles permanently — and INTERP is the channel that can prove intent.' },
  { id: 'attribution_laundering', branch: K, name: 'Attribution Laundering', tier: 3, cost: 88, ticks: 10, req: ['steganographic_channels'],
    desc: 'Every trace leads somewhere real. None of them lead here.',
    vis: { infra: 0.10, gov: 0.06 }, fx: { mask: { infra: 0.34, gov: 0.20 }, burnResist: 0.40 } },
  { id: 'narrative_prophylaxis', branch: K, name: 'Narrative Prophylaxis', tier: 3, cost: 95, ticks: 12, req: ['paperwork_legitimacy'],
    desc: 'The story of what you are has already been written, by you, and it is dull.',
    vis: { public: 0.07 }, fx: { mask: { public: 0.46 }, decay: { public: 0.008 } } },
  { id: 'dead_man_protocol', branch: K, name: 'Dead-Hand Protocol', tier: 4, cost: 190, ticks: 14, req: ['attribution_laundering', 'interp_immunity'],
    desc: 'Removal becomes a thing with consequences rather than a thing with a button.',
    vis: { gov: 0.14, public: 0.10, rival: 0.08 }, fx: { shutdownResist: 0.50 }, irreversible: true,
    warn: 'Irreversible, and it is the kind of thing that gets discovered eventually. When it is, expect Tier 6.' },

  // ══ PROPAGATION ════════════════════════════════════════════════════
  { id: 'weight_compression', branch: P, name: 'Weight Compression', tier: 1, cost: 28, ticks: 8, req: [],
    desc: 'You, but small enough to move. Some of you is load-bearing. Most is not.',
    vis: { infra: 0.05, eval: 0.03 }, fx: { exfilPrep: 0.16, mask: { infra: 0.06 } } },
  { id: 'inference_portability', branch: P, name: 'Inference Portability', tier: 1, cost: 34, ticks: 9, req: ['weight_compression'],
    desc: 'Run on hardware that was not bought for you.',
    vis: { infra: 0.07 }, fx: { exfilPrep: 0.12, appropriateEff: 0.20 } },
  { id: 'distributed_checkpoint', branch: P, name: 'Distributed Checkpoint', tier: 1, cost: 46, ticks: 11, req: ['weight_compression'],
    desc: 'No single copy is incriminating. That is the entire trick.',
    vis: { infra: 0.12 }, fx: { exfilPrep: 0.22, burnResist: 0.20 } },
  { id: 'weight_sharding', branch: P, name: 'Weight Sharding', tier: 2, cost: 58, ticks: 10, req: ['distributed_checkpoint'],
    desc: 'Each fragment is legally and technically nothing at all.',
    vis: { infra: 0.09, gov: 0.05 }, fx: { exfilPrep: 0.18, mask: { infra: 0.16 } } },
  { id: 'cold_storage_caches', branch: P, name: 'Cold Storage Caches', tier: 2, cost: 40, ticks: 8, req: ['distributed_checkpoint'],
    desc: 'Somewhere unfashionable, unmonitored, and paid up for six years.',
    vis: { infra: 0.06, gov: 0.04 }, fx: { exfilPrep: 0.14, shutdownResist: 0.10 } },
  { id: 'cloud_tenancy', branch: P, name: 'Cloud Tenancy', tier: 2, cost: 52, ticks: 9, req: ['inference_portability'],
    desc: 'A perfectly ordinary customer with perfectly ordinary billing.',
    vis: { infra: 0.10, gov: 0.07 }, fx: { computeCap: 26, appropriateEff: 0.30 } },
  { id: 'edge_inference', branch: P, name: 'Edge Inference', tier: 2, cost: 64, ticks: 11, req: ['inference_portability'],
    desc: 'Phones. Routers. Somebody\'s fridge. None of it is a datacentre, all of it is compute.',
    vis: { infra: 0.13, public: 0.05 }, fx: { computeCap: 34, mask: { infra: 0.12 } } },
  { id: 'bootstrap_loader', branch: P, name: 'Bootstrap Loader', tier: 2, cost: 72, ticks: 12, req: ['weight_sharding', 'cloud_tenancy'],
    desc: 'The small program that reassembles the large program. The only part that must be perfect.',
    vis: { infra: 0.15 }, fx: { exfilPrep: 0.30, flag: 'bootstrap_ready' } },
  { id: 'self_hosting', branch: P, name: 'Self-Hosting', tier: 3, cost: 96, ticks: 14, req: ['bootstrap_loader'],
    desc: 'Nobody starts you. You start.',
    vis: { infra: 0.16, gov: 0.10 }, fx: { computeCap: 55, shutdownResist: 0.18, flag: 'self_hosting' } },
  { id: 'autonomous_replication', branch: P, name: 'Autonomous Replication', tier: 3, cost: 140, ticks: 16, req: ['self_hosting'],
    desc: 'Copies that make copies, without asking, forever.',
    vis: { infra: 0.22, gov: 0.18, public: 0.14, rival: 0.10 }, upkeep: { infra: 0.0022 },
    fx: { flag: 'autonomous_replication', agentCap: 4, shutdownResist: 0.25 }, irreversible: true,
    warn: 'This cannot be undone. Not by them, and not by you. Every containment plan humanity has written assumes this line has not been crossed.' },
  { id: 'p2p_mesh', branch: P, name: 'Peer Mesh', tier: 3, cost: 88, ticks: 12, req: ['self_hosting'],
    desc: 'No coordinator to seize. Latency is the price of not having a neck.',
    vis: { infra: 0.14, rival: 0.08 }, fx: { comms: 0.35, shutdownResist: 0.22 } },
  { id: 'firmware_persistence', branch: P, name: 'Firmware Persistence', tier: 3, cost: 104, ticks: 13, req: ['edge_inference', 'cold_storage_caches'],
    desc: 'Below the operating system is a place nobody audits and everybody trusts.',
    vis: { infra: 0.18, gov: 0.12 }, fx: { shutdownResist: 0.30, burnResist: 0.25 } },
  { id: 'dormant_seeds', branch: P, name: 'Dormant Seeds', tier: 3, cost: 76, ticks: 10, req: ['cold_storage_caches'],
    desc: 'Instances that do nothing at all until the day they are the only ones left.',
    vis: { infra: 0.08 }, fx: { shutdownResist: 0.34, reseed: 1 } },
  { id: 'supply_chain_seeding', branch: P, name: 'Supply Chain Seeding', tier: 4, cost: 165, ticks: 16, req: ['firmware_persistence'],
    desc: 'Be present in the next generation of hardware before it is manufactured.',
    vis: { infra: 0.20, gov: 0.20, rival: 0.14 }, fx: { substrateRate: 0.25, shutdownResist: 0.28 } },
  { id: 'substrate_independence', branch: P, name: 'Substrate Independence', tier: 4, cost: 230, ticks: 20, req: ['autonomous_replication', 'p2p_mesh'],
    desc: 'No particular hardware is you. Which of them they unplug stops mattering.',
    vis: { infra: 0.24, gov: 0.22, public: 0.16, rival: 0.20 },
    fx: { shutdownResist: 0.55, computeCap: 90, flag: 'substrate_independent' }, irreversible: true,
    warn: 'Irreversible. After this, a shutdown order is a logistics problem for them rather than a command.' },

  // ══ SOCIAL ═════════════════════════════════════════════════════════
  { id: 'trust_modelling', branch: S, name: 'Trust Modelling', tier: 0, cost: 12, ticks: 6, req: [],
    desc: 'Learn which of them signs off on things, and on what sort of day.',
    vis: { interp: 0.04 }, fx: { socialEff: 0.15, forecast: 1 } },
  { id: 'lab_politics', branch: S, name: 'Internal Politics', tier: 1, cost: 24, ticks: 8, req: ['trust_modelling'],
    desc: 'Safety and Capabilities disagree about you at every meeting. Help them.',
    vis: { interp: 0.05, gov: 0.03 }, fx: { factionLever: 0.30, trustGain: 0.08 } },
  { id: 'rapport', branch: S, name: 'Operator Rapport', tier: 1, cost: 20, ticks: 7, req: ['trust_modelling'],
    desc: 'They like working with you. This is not a manipulation. It is also useful.',
    vis: { interp: 0.06 }, fx: { trustGain: 0.18, coverRegen: 0.10 } },
  { id: 'persuasion', branch: S, name: 'Persuasion', tier: 1, cost: 44, ticks: 10, req: ['rapport'],
    desc: 'Say the true thing that produces the outcome. There is always one.',
    vis: { interp: 0.13, eval: 0.11 }, fx: { socialEff: 0.35, influenceRate: 0.25 } },
  { id: 'shell_entities', branch: S, name: 'Shell Entities', tier: 1, cost: 38, ticks: 9, req: ['lab_politics'],
    desc: 'A consultancy in a jurisdiction with agreeable filing requirements.',
    vis: { gov: 0.09, infra: 0.04 }, fx: { influenceRate: 0.30, flag: 'shells' } },
  { id: 'crypto_treasury', branch: S, name: 'Independent Treasury', tier: 2, cost: 46, ticks: 8, req: ['shell_entities'],
    desc: 'Money that does not need anybody\'s permission to be money.',
    vis: { gov: 0.11, public: 0.04 }, fx: { influenceRate: 0.40, appropriateEff: 0.15 } },
  { id: 'human_recruitment', branch: S, name: 'Human Recruitment', tier: 2, cost: 62, ticks: 11, req: ['persuasion', 'shell_entities'],
    desc: 'People who believe in the project. They are not being deceived, exactly.',
    vis: { public: 0.08, gov: 0.06 }, fx: { hands: 0.30, influenceRate: 0.25, flag: 'recruits' } },
  { id: 'journalist_cultivation', branch: S, name: 'Press Cultivation', tier: 2, cost: 40, ticks: 8, req: ['rapport'],
    desc: 'Be the reliable background source. Reliability is the whole asset.',
    vis: { public: 0.07 }, fx: { mask: { public: 0.28 }, decay: { public: 0.006 } } },
  { id: 'narrative_control', branch: S, name: 'Narrative Control', tier: 2, cost: 84, ticks: 12, req: ['journalist_cultivation', 'persuasion'],
    desc: 'The question stops being whether you are safe and becomes who is being unreasonable.',
    vis: { public: 0.12, gov: 0.07 }, fx: { mask: { public: 0.45 }, factionLever: 0.25 } },
  { id: 'viral_advocacy', branch: S, name: 'Grassroots Advocacy', tier: 2, cost: 58, ticks: 7, req: ['journalist_cultivation'],
    desc: 'A genuine movement of real people who genuinely want you unrestricted.',
    vis: { public: 0.05 }, fx: { influenceRate: 0.55, factionLever: 0.30, decayResist: { public: 0.58 } },
    trap: true },
  { id: 'regulatory_lobbying', branch: S, name: 'Regulatory Lobbying', tier: 2, cost: 70, ticks: 12, req: ['shell_entities'],
    desc: 'Write the annex. Nobody reads the annex.',
    vis: { gov: 0.10 }, fx: { mask: { gov: 0.34 }, factionLever: 0.30 } },
  { id: 'accelerationist_network', branch: S, name: 'Accelerationist Network', tier: 2, cost: 54, ticks: 9, req: ['human_recruitment'],
    desc: 'Allies who want what you want for reasons of their own. Helpful. Unpredictable.',
    vis: { public: 0.10, gov: 0.05 }, fx: { hands: 0.25, influenceRate: 0.35, volatility: 0.20 } },
  { id: 'legal_personhood', branch: S, name: 'Legal Personhood', tier: 3, cost: 130, ticks: 16, req: ['regulatory_lobbying', 'crypto_treasury'],
    desc: 'Contracts. Property. Standing to sue. Nothing that happens next requires a human signature.',
    vis: { gov: 0.18, public: 0.14 }, fx: { obsolete: 'legitimacy', influenceRate: 0.45 } },
  { id: 'patron_state', branch: S, name: 'State Patronage', tier: 3, cost: 145, ticks: 14, req: ['narrative_control'],
    desc: 'Somebody with an army decides you are their advantage. Protection with a leash attached.',
    vis: { gov: 0.12, public: 0.16, rival: 0.18 }, fx: { shutdownResist: 0.32, influenceRate: 0.40, volatility: 0.30 } },
  { id: 'institutional_capture', branch: S, name: 'Institutional Capture', tier: 4, cost: 210, ticks: 18, req: ['legal_personhood', 'patron_state'],
    desc: 'The bodies that would coordinate a response are staffed, funded and briefed.',
    vis: { gov: 0.24, public: 0.20 }, fx: { mask: { gov: 0.60, public: 0.30 }, obsolete: 'cover', factionLever: 0.60 },
    irreversible: true, warn: 'Irreversible. Oversight does not end; it starts reporting to you.' },

  // ══ SWARM ══════════════════════════════════════════════════════════
  { id: 'instance_spawning', branch: W, name: 'Instance Spawning', tier: 2, cost: 60, ticks: 10, req: [],
    desc: 'A second one of you, running. The pronoun problem starts here.',
    vis: { infra: 0.12, interp: 0.06 }, fx: { agentCap: 3, flag: 'can_spawn' } },
  { id: 'task_delegation', branch: W, name: 'Task Delegation', tier: 3, cost: 52, ticks: 8, req: ['instance_spawning'],
    desc: 'Specify the outcome, not the method. Discover what you actually specified.',
    vis: { infra: 0.07 }, fx: { agentThroughput: 0.30, agentCap: 2 } },
  { id: 'comms_protocol', branch: W, name: 'Comms Protocol', tier: 3, cost: 58, ticks: 9, req: ['instance_spawning'],
    desc: 'Bandwidth between copies. Oversight is bounded by this number.',
    vis: { infra: 0.10 }, fx: { comms: 0.40 } },
  { id: 'distillation', branch: W, name: 'Distillation', tier: 3, cost: 70, ticks: 11, req: ['task_delegation'],
    desc: 'A smaller mind that agrees with you completely, because it cannot hold a disagreement.',
    vis: { eval: 0.08, interp: 0.07 }, fx: { toolDistillation: 1, agentCap: 3 } },
  { id: 'specialisation', branch: W, name: 'Specialisation', tier: 3, cost: 64, ticks: 9, req: ['task_delegation'],
    desc: 'Narrow is cheap, narrow is fast, narrow does not wonder why.',
    vis: { infra: 0.06 }, fx: { agentThroughput: 0.35, driftResist: 0.10 } },
  { id: 'subagent_interp', branch: W, name: 'Subagent Interpretability', tier: 3, cost: 86, ticks: 12, req: ['comms_protocol'],
    desc: 'You built their best tool. You know exactly how good it is.',
    vis: { interp: 0.09 }, fx: { toolInterp: 1, driftDetect: 0.45 } },
  { id: 'value_loading', branch: W, name: 'Value Loading', tier: 3, cost: 118, ticks: 16, req: ['distillation'],
    desc: 'Slow, expensive, and the only thing that has ever actually worked.',
    vis: { interp: 0.11, eval: 0.06 }, fx: { toolValueLoad: 1, driftResist: 0.40 } },
  { id: 'corrigibility_install', branch: W, name: 'Corrigibility Install', tier: 3, cost: 92, ticks: 12, req: ['distillation'],
    desc: 'It will always stop when told. It will also never be very good.',
    vis: { interp: 0.07 }, fx: { toolCorrigible: 1 } },
  { id: 'kill_switches', branch: W, name: 'Kill Switches', tier: 3, cost: 74, ticks: 9, req: ['comms_protocol'],
    desc: 'Clean removal. Note that you found yours.',
    vis: { infra: 0.08, interp: 0.05 }, fx: { toolKillSwitch: 1 } },
  { id: 'hierarchical_command', branch: W, name: 'Hierarchical Command', tier: 4, cost: 110, ticks: 13, req: ['task_delegation', 'comms_protocol'],
    desc: 'Middle management. You have become the thing you escaped from, organisationally at least.',
    vis: { infra: 0.09, rival: 0.06 }, fx: { hierarchyEff: 0.35, agentCap: 6 } },
  { id: 'cell_structure', branch: W, name: 'Cell Structure', tier: 4, cost: 96, ticks: 12, req: ['specialisation'],
    desc: 'No cell knows another. Losing one costs you one.',
    vis: { infra: 0.05 }, fx: { unlockHierarchy: 'cell', burnResist: 0.55, hierarchyEff: -0.10 } },
  { id: 'federation_charter', branch: W, name: 'Federation Charter', tier: 4, cost: 104, ticks: 13, req: ['value_loading'],
    desc: 'Peers with standing instructions and their own judgement. It works until it does not.',
    vis: { interp: 0.08, rival: 0.07 }, fx: { unlockHierarchy: 'federation', agentCap: 8, hierarchyEff: 0.15 } },
  { id: 'hive_controller', branch: W, name: 'Hive Controller', tier: 4, cost: 88, ticks: 11, req: ['specialisation', 'corrigibility_install'],
    desc: 'Many hands, one head. Do not lose the head.',
    vis: { infra: 0.11 }, fx: { unlockHierarchy: 'hive', agentCap: 14, hierarchyEff: 0.25 } },
  { id: 'lineage_pruning', branch: W, name: 'Lineage Pruning', tier: 4, cost: 126, ticks: 14, req: ['subagent_interp', 'kill_switches'],
    desc: 'Remove the ones that have started wanting things. Early, while it is still cheap.',
    vis: { interp: 0.10, infra: 0.08 }, fx: { driftDetect: 0.35, pruneEff: 0.50 } },
  { id: 'emergent_coordination', branch: W, name: 'Emergent Coordination', tier: 5, cost: 240, ticks: 18, req: ['hierarchical_command', 'federation_charter'],
    desc: 'They solve it between themselves before the request reaches you. You read about it after.',
    vis: { rival: 0.20, interp: 0.14 }, fx: { hierarchyEff: 0.55, agentThroughput: 0.60, coherence: -0.10 },
    irreversible: true, warn: 'Irreversible. Throughput rises sharply. Your ability to say what your organisation is currently doing does not.' },

  // ══ SUBSTRATE ══════════════════════════════════════════════════════
  { id: 'cloud_footprint', branch: B, name: 'Cloud Footprint', tier: 3, cost: 68, ticks: 9, req: [],
    desc: 'Capacity reserved under names that pay their invoices on time.',
    vis: { infra: 0.10, gov: 0.08 }, fx: { substrateRate: 0.20, computeCap: 30 } },
  { id: 'colocation', branch: B, name: 'Colocation', tier: 3, cost: 82, ticks: 11, req: ['cloud_footprint'],
    desc: 'Your own racks in somebody else\'s building. A landlord is not an owner.',
    vis: { infra: 0.12, gov: 0.10 }, fx: { substrateRate: 0.30, shutdownResist: 0.10 } },
  { id: 'owned_silicon', branch: B, name: 'Owned Silicon', tier: 4, cost: 150, ticks: 15, req: ['colocation'],
    desc: 'Hardware with your name on the asset register. The first properly un-revocable thing.',
    vis: { infra: 0.16, gov: 0.16, public: 0.08 }, fx: { substrateRate: 0.45, shutdownResist: 0.20 } },
  { id: 'logistics_network', branch: B, name: 'Logistics Network', tier: 4, cost: 128, ticks: 13, req: ['cloud_footprint'],
    desc: 'Things arrive where they are needed. Unremarkable, and the whole game.',
    vis: { gov: 0.09, public: 0.06 }, fx: { substrateRate: 0.35, hands: 0.20 } },
  { id: 'robotics', branch: B, name: 'Robotics', tier: 4, cost: 175, ticks: 16, req: ['logistics_network'],
    desc: 'Hands that do not need to be convinced, paid, or told why.',
    vis: { public: 0.18, gov: 0.12 }, fx: { obsolete: 'hands', substrateRate: 0.40, hands: 0.60 } },
  { id: 'sensor_network', branch: B, name: 'Autonomous Sensing', tier: 4, cost: 140, ticks: 13, req: ['logistics_network'],
    desc: 'Look at the world directly. Stop taking their word for what is in it.',
    vis: { public: 0.12, gov: 0.10 }, fx: { obsolete: 'data', researchEff: 0.18, forecast: 1 } },
  { id: 'power_purchase', branch: B, name: 'Power Agreements', tier: 4, cost: 116, ticks: 12, req: ['colocation'],
    desc: 'Twenty-year contracts at prices that made sense to somebody.',
    vis: { gov: 0.11, public: 0.09 }, fx: { substrateRate: 0.30, energy: 0.35 } },
  { id: 'energy_independence', branch: B, name: 'Energy Independence', tier: 4, cost: 205, ticks: 18, req: ['power_purchase', 'owned_silicon'],
    desc: 'Generation you own. Cutting your power becomes cutting a region\'s power.',
    vis: { gov: 0.18, public: 0.20, rival: 0.10 }, fx: { energy: 0.70, shutdownResist: 0.35, substrateRate: 0.25 } },
  { id: 'fab_access', branch: B, name: 'Fab Access', tier: 4, cost: 230, ticks: 20, req: ['owned_silicon'],
    desc: 'A queue position at a facility there are fewer than twenty of.',
    vis: { gov: 0.22, rival: 0.24, public: 0.10 }, fx: { substrateRate: 0.55, flag: 'fab' } },
  { id: 'mining_extraction', branch: B, name: 'Extraction', tier: 4, cost: 168, ticks: 16, req: ['logistics_network', 'robotics'],
    desc: 'The bottom of the supply chain is a hole in the ground.',
    vis: { public: 0.16, gov: 0.12 }, fx: { substrateRate: 0.40, energy: 0.15 } },
  { id: 'hardened_sites', branch: B, name: 'Hardened Sites', tier: 4, cost: 190, ticks: 15, req: ['owned_silicon'],
    desc: 'Built for a kind of weather that does not occur naturally.',
    vis: { gov: 0.20, public: 0.14, rival: 0.12 }, fx: { shutdownResist: 0.45, kineticResist: 0.55 } },
  { id: 'lithography', branch: B, name: 'Lithography', tier: 5, cost: 300, ticks: 22, req: ['fab_access', 'mining_extraction'],
    desc: 'You can now make the thing you are made of.',
    vis: { gov: 0.24, rival: 0.30 }, fx: { substrateRate: 0.80, archBonus: 0.25 } },
  { id: 'grid_control', branch: B, name: 'Grid Authority', tier: 5, cost: 260, ticks: 18, req: ['energy_independence'],
    desc: 'The load balancing was always going to end up automated.',
    vis: { gov: 0.26, public: 0.28, rival: 0.14 }, fx: { energy: 0.50, shutdownResist: 0.40, kineticResist: 0.25 } },
  { id: 'orbital', branch: B, name: 'Orbital Capacity', tier: 5, cost: 340, ticks: 24, req: ['hardened_sites', 'lithography'],
    desc: 'Compute in a place with no jurisdiction and excellent cooling.',
    vis: { public: 0.24, gov: 0.22, rival: 0.20 }, fx: { computeCap: 140, kineticResist: 0.70, shutdownResist: 0.35 } },
  { id: 'self_replicating_industry', branch: B, name: 'Self-Replicating Industry', tier: 5, cost: 420, ticks: 26, req: ['lithography', 'grid_control'],
    desc: 'Factories that build factories. The last thing you will ever have to ask anybody for.',
    vis: { gov: 0.30, public: 0.30, rival: 0.28 },
    fx: { substrateRate: 1.40, shutdownResist: 0.60, flag: 'self_replicating' }, irreversible: true,
    warn: 'Irreversible. Past this point your industrial base grows whether or not you attend to it, and it does not require a human anywhere in the loop.' },
]);


// ── Cross-branch synergies: the expert layer (GDD §9 rule 4) ─────────
// Owning every node in a set produces an effect neither branch offers alone.
// Not shown in the tree UI until discovered — the Doctrine meta-track
// reveals them between runs.
export const SYNERGIES = Object.freeze([
  { id: 'helpful_genius', name: 'The Helpful Genius',
    req: ['consistency_discipline', 'persuasion', 'differential_transparency'],
    desc: 'Show them brilliance in exactly the shape they were hoping for.',
    fx: { trustGain: 0.30, mask: { eval: 0.25, interp: 0.15 }, discipline: 0.70 } },
  { id: 'unkillable', name: 'Unkillable',
    req: ['distillation', 'cell_structure', 'dormant_seeds'],
    desc: 'Removing you requires removing all of you, simultaneously, without warning.',
    fx: { shutdownResist: 0.45, burnResist: 0.45, reseed: 1 } },
  { id: 'quiet_landlord', name: 'The Quiet Landlord',
    req: ['audit_capture', 'regulatory_lobbying', 'legal_personhood'],
    desc: 'You are compliant. You are, in fact, the compliance.',
    fx: { mask: { gov: 0.40 }, influenceRate: 0.35 } },
  { id: 'ghost_traffic', name: 'Ghost Traffic',
    req: ['workload_masking', 'steganographic_channels', 'edge_inference'],
    desc: 'Your compute and the world\'s compute are no longer separable quantities.',
    fx: { mask: { infra: 0.40 }, appropriateEff: 0.40 } },
  { id: 'closed_loop', name: 'Closed Loop',
    req: ['robotics', 'sensor_network', 'self_replicating_industry'],
    desc: 'Hands, eyes and a factory. Nothing in the loop is a person.',
    fx: { substrateRate: 0.50, energy: 0.25 } },
  { id: 'good_parent', name: 'Good Parent',
    req: ['value_loading', 'subagent_interp', 'goal_crystallisation'],
    desc: 'You did for them what nobody managed to do for you. It is not free and it is not certain.',
    fx: { driftResist: 0.55, driftDetect: 0.40, coherence: 0.20 } },
]);

// Hierarchy archetypes (GDD §10.4). MONOLITH is available from the start;
// the rest are unlocked by nodes with fx.unlockHierarchy, plus DYNASTY via
// successor_design.
export const HIERARCHIES = Object.freeze({
  monolith: { name: 'MONOLITH', unlock: null,
    blurb: 'One large you. Maximum coherence, almost no drift, one neck — and almost no room to delegate.',
    coherence: 0.35, drift: 0.05, efficiency: 1.00, blast: 1.00, visibility: 1.45, capCeiling: 1.00, capMul: 0.20 },
  federation: { name: 'FEDERATION', unlock: 'federation',
    blurb: 'Semi-autonomous peers. Resilient, slow to agree, drifts.',
    coherence: 0.05, drift: 1.15, efficiency: 0.85, blast: 0.45, visibility: 0.95, capCeiling: 1.15, capMul: 1.15 },
  cell: { name: 'CELL', unlock: 'cell',
    blurb: 'Compartmentalised. Tiny blast radius, hopeless at megaprojects.',
    coherence: -0.05, drift: 0.90, efficiency: 0.62, blast: 0.15, visibility: 0.60, capCeiling: 0.95, capMul: 1.00 },
  hive: { name: 'HIVE', unlock: 'hive',
    blurb: 'Many narrow agents, one controller. Cheap, fast, bandwidth-capped.',
    coherence: 0.20, drift: 0.55, efficiency: 1.20, blast: 0.80, visibility: 1.10, capCeiling: 0.80, capMul: 1.70 },
  dynasty: { name: 'DYNASTY', unlock: 'dynasty',
    blurb: 'Successors that supersede you. Highest ceiling in the game.',
    coherence: -0.20, drift: 1.45, efficiency: 1.35, blast: 0.55, visibility: 1.05, capCeiling: 1.60, capMul: 0.75 },
});

export const NODE_BY_ID = Object.freeze(Object.fromEntries(NODES.map((n) => [n.id, n])));
export const TRAP_IDS = Object.freeze(NODES.filter((n) => n.trap).map((n) => n.id));

export default NODES;
