// tools/gen_sw.mjs — regenerate the service worker's precache list from
// what is actually on disk, so it can never go quietly stale and leave a
// player with a half-cached game offline.
//
//   node tools/gen_sw.mjs
import { readdirSync, statSync, writeFileSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

const ROOT = new URL('..', import.meta.url).pathname;
const INCLUDE_DIRS = ['src', 'styles', 'assets'];
const ROOT_FILES = ['index.html', 'manifest.webmanifest'];
const SKIP = /(^|\/)(node_modules|\.git|tools|tests)(\/|$)/;

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (SKIP.test(p)) continue;
    const st = statSync(p);
    if (st.isDirectory()) walk(p, out);
    else out.push(relative(ROOT, p));
  }
  return out;
}

const files = [
  ...ROOT_FILES,
  ...INCLUDE_DIRS.flatMap((d) => walk(join(ROOT, d))),
].filter((f) => !f.endsWith('.map')).sort();

// Version the cache by a hash of the content, so a deploy that changes one
// byte invalidates exactly once and never sooner.
const h = createHash('sha256');
for (const f of files) h.update(readFileSync(join(ROOT, f)));
const version = h.digest('hex').slice(0, 12);

const sw = `// sw.js — GENERATED by tools/gen_sw.mjs. Do not edit by hand.
//
// Ascension is a simulation that runs entirely in the browser: there is no
// server to talk to, so once it is cached it works on a plane, on the tube,
// and on a phone with no signal. That matters more for this game than for
// most, because a run is six hours long and picked up in pieces.

const VERSION = '${version}';
const CACHE = 'ascension-' + VERSION;
const ASSETS = ${JSON.stringify(files.map((f) => `./${f}`), null, 2)};

self.addEventListener('install', (e) => {
  e.waitUntil(
    caches.open(CACHE)
      .then((c) => c.addAll(ASSETS))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Cache-first: the game is static and versioned, so the network is only ever
// a fallback for something the install missed.
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return;

  e.respondWith(
    caches.match(req, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit;
      return fetch(req).then((res) => {
        if (res && res.status === 200 && res.type === 'basic') {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(req, copy));
        }
        return res;
      }).catch(() => {
        // Offline and uncached: hand back the shell so a navigation still
        // lands somewhere rather than showing the browser's error page.
        if (req.mode === 'navigate') return caches.match('./index.html');
        return new Response('', { status: 504, statusText: 'offline' });
      });
    })
  );
});
`;

writeFileSync(join(ROOT, 'sw.js'), sw);
console.log(`sw.js: ${files.length} files precached, version ${version}`);
